[package]
name = "rust_sample_cpp"
version = "0.1.0"
authors = ["Hatter Jiang <jht5945@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
cpp = "0.5.3"

[build-dependencies]
cpp_build = "0.5.3"

